-- ================================================================
--  CREDITXA — Complete Database Schema (v2 — fixed & consolidated)
--  Single file. Paste ENTIRELY into Supabase SQL Editor → Run.
--
--  This script always starts by dropping every Creditxa object it
--  knows about, so you can paste this same file again in the
--  future to wipe and rebuild a perfectly clean database.
--  It does NOT touch auth.users — Supabase manages that separately.
--
--  WHAT THIS VERSION FIXES vs the original schema:
--   1. Real Row-Level-Security: the anon key could previously
--      INSERT/UPDATE/SELECT every row of every table (including
--      other people's KYC data). Public writes now only happen
--      through SECURITY DEFINER functions (RPCs) that validate
--      input server-side; direct table access is limited to the
--      record owner (a logged-in client) or a verified admin.
--   2. admin_users now links to a real Supabase Auth account
--      (auth_user_id) instead of a password hard-coded in HTML.
--   3. activity_log now records BOTH admin actions and client
--      account activity (signup / email verified / login /
--      logout), tagged with actor_type, so the admin panel can
--      show a real activity feed.
--   4. Application numbers / client codes are generated by the
--      database (sequences) instead of Date.now() in the browser,
--      removing a duplicate-key race condition.
-- ================================================================

-- ── 0. CLEAN SLATE ─────────────────────────────────────────────
drop trigger if exists on_auth_user_created  on auth.users;
drop trigger if exists on_auth_user_verified on auth.users;

drop view if exists vw_clients_overview   cascade;
drop view if exists vw_payments_full      cascade;
drop view if exists vw_applications_full  cascade;
drop view if exists vw_dashboard_summary  cascade;
drop view if exists vw_activity_feed      cascade;

drop function if exists handle_new_auth_user()        cascade;
drop function if exists handle_auth_user_verified()    cascade;
drop function if exists log_activity(text,text,text,uuid) cascade;
drop function if exists admin_login_check()            cascade;
drop function if exists submit_loan_application(text,text,text,text,text,date,text,text,text,text,numeric,text,text,text,numeric,integer,numeric,text,numeric) cascade;
drop function if exists admin_create_client(text,text,text,text,text,date,numeric) cascade;
drop function if exists is_admin()                      cascade;
drop function if exists update_updated_at()             cascade;

drop table if exists activity_log           cascade;
drop table if exists payments               cascade;
drop table if exists loans                  cascade;
drop table if exists loan_applications      cascade;
drop table if exists clients                cascade;
drop table if exists messages               cascade;
drop table if exists newsletter_subscribers cascade;
drop table if exists admin_users            cascade;
drop table if exists system_settings        cascade;

drop sequence if exists application_no_seq;
drop sequence if exists client_code_seq;

-- ── 1. CLIENTS ──────────────────────────────────────────────────
CREATE TABLE clients (
  id                 UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  client_code        TEXT         UNIQUE NOT NULL,
  full_name          TEXT         NOT NULL,
  email              TEXT         UNIQUE NOT NULL,
  nif                TEXT         UNIQUE NOT NULL,
  phone              TEXT,
  address            TEXT,
  date_of_birth      DATE,
  monthly_income     NUMERIC(12,2),
  nationality        TEXT,
  residence_status   TEXT         CHECK (residence_status IN ('citizen','eu_resident','non_eu_resident','non_resident')),
  id_document_type   TEXT         CHECK (id_document_type IN ('cc','passport','residence_permit')),
  id_document_number TEXT,
  iban               TEXT,
  employment_status  TEXT         CHECK (employment_status IN ('employed','self_employed','business_owner','unemployed','retired','student')),
  kyc_verified       BOOLEAN      NOT NULL DEFAULT false,
  kyc_verified_at    TIMESTAMPTZ,
  status             TEXT         NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','blocked','overdue')),
  auth_user_id       UUID         UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT chk_client_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  CONSTRAINT chk_client_nif   CHECK (nif ~ '^[0-9]{9}$')
);

-- ── 2. LOAN APPLICATIONS ────────────────────────────────────────
CREATE TABLE loan_applications (
  id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  application_no  TEXT         UNIQUE NOT NULL,
  client_id       UUID         NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  loan_type       TEXT         NOT NULL CHECK (loan_type IN ('personal','mortgage','car','consolidation')),
  amount          NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  term_months     INTEGER      NOT NULL CHECK (term_months > 0),
  annual_rate     NUMERIC(6,4) NOT NULL CHECK (annual_rate >= 0),
  monthly_payment NUMERIC(12,2),
  loan_purpose    TEXT,
  existing_debts  NUMERIC(12,2) DEFAULT 0,
  source          TEXT         DEFAULT 'website',
  status          TEXT         NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','review','approved','rejected')),
  notes           TEXT,
  reviewed_by     TEXT,
  reviewed_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── 3. LOANS (active contracts) ─────────────────────────────────
CREATE TABLE loans (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  contract_no      TEXT         UNIQUE NOT NULL,
  application_id   UUID         UNIQUE REFERENCES loan_applications(id),
  client_id        UUID         NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  loan_type        TEXT         NOT NULL CHECK (loan_type IN ('personal','mortgage','car','consolidation')),
  principal        NUMERIC(12,2) NOT NULL CHECK (principal > 0),
  annual_rate      NUMERIC(6,4) NOT NULL CHECK (annual_rate >= 0),
  term_months      INTEGER      NOT NULL CHECK (term_months > 0),
  monthly_payment  NUMERIC(12,2) NOT NULL,
  start_date       DATE         NOT NULL,
  end_date         DATE         NOT NULL,
  amount_paid      NUMERIC(12,2) NOT NULL DEFAULT 0,
  amount_remaining NUMERIC(12,2) NOT NULL,
  status           TEXT         NOT NULL DEFAULT 'active' CHECK (status IN ('active','paid_off','defaulted','early_settled')),
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT chk_loan_dates CHECK (end_date > start_date)
);

-- ── 4. PAYMENTS ─────────────────────────────────────────────────
CREATE TABLE payments (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_ref    TEXT         UNIQUE NOT NULL,
  loan_id        UUID         NOT NULL REFERENCES loans(id) ON DELETE CASCADE,
  client_id      UUID         NOT NULL REFERENCES clients(id),
  amount         NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  payment_method TEXT         NOT NULL DEFAULT 'bank_transfer' CHECK (payment_method IN ('bank_transfer','mb_way','direct_debit','cash','other')),
  payment_date   DATE         NOT NULL DEFAULT CURRENT_DATE,
  reference      TEXT,
  status         TEXT         NOT NULL DEFAULT 'paid' CHECK (status IN ('paid','failed','pending','refunded')),
  notes          TEXT,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── 5. MESSAGES (contact form) ──────────────────────────────────
CREATE TABLE messages (
  id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT         NOT NULL,
  email      TEXT         NOT NULL,
  subject    TEXT         NOT NULL,
  body       TEXT         NOT NULL,
  status     TEXT         NOT NULL DEFAULT 'unread' CHECK (status IN ('unread','read','replied')),
  reply_body TEXT,
  replied_at TIMESTAMPTZ,
  replied_by TEXT,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── 6. NEWSLETTER ───────────────────────────────────────────────
CREATE TABLE newsletter_subscribers (
  id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  email      TEXT         UNIQUE NOT NULL,
  source     TEXT         DEFAULT 'website',
  subscribed BOOLEAN      NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── 7. ADMIN USERS ──────────────────────────────────────────────
-- auth_user_id links this row to a real Supabase Auth account.
-- It starts NULL and is filled in automatically the first time
-- that admin successfully signs in (see admin_login_check() below).
CREATE TABLE admin_users (
  id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  email        TEXT         UNIQUE NOT NULL,
  name         TEXT         NOT NULL,
  role         TEXT         NOT NULL DEFAULT 'admin' CHECK (role IN ('super_admin','admin','viewer')),
  active       BOOLEAN      NOT NULL DEFAULT true,
  auth_user_id UUID         UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
  last_login   TIMESTAMPTZ,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── 8. SYSTEM SETTINGS ──────────────────────────────────────────
CREATE TABLE system_settings (
  key         TEXT         PRIMARY KEY,
  value       TEXT         NOT NULL,
  description TEXT,
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── 9. ACTIVITY LOG (admin actions + client account activity) ───
CREATE TABLE activity_log (
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_type  TEXT         NOT NULL DEFAULT 'admin' CHECK (actor_type IN ('admin','client','system')),
  actor_email TEXT         NOT NULL,
  action      TEXT         NOT NULL,
  entity_type TEXT,
  entity_id   UUID,
  details     TEXT,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ── SEQUENCES for server-generated codes (avoids JS Date.now() collisions) ──
CREATE SEQUENCE application_no_seq START 1;
CREATE SEQUENCE client_code_seq    START 1;

-- ── AUTO-UPDATE TRIGGER ──────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;
CREATE TRIGGER trg_clients_updated BEFORE UPDATE ON clients          FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_apps_updated    BEFORE UPDATE ON loan_applications FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_loans_updated   BEFORE UPDATE ON loans             FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ── INDEXES ─────────────────────────────────────────────────────
CREATE INDEX idx_clients_email     ON clients(email);
CREATE INDEX idx_clients_nif       ON clients(nif);
CREATE INDEX idx_clients_auth      ON clients(auth_user_id);
CREATE INDEX idx_apps_client       ON loan_applications(client_id);
CREATE INDEX idx_apps_status       ON loan_applications(status);
CREATE INDEX idx_apps_created      ON loan_applications(created_at DESC);
CREATE INDEX idx_loans_client      ON loans(client_id);
CREATE INDEX idx_loans_status      ON loans(status);
CREATE INDEX idx_payments_loan     ON payments(loan_id);
CREATE INDEX idx_payments_client   ON payments(client_id);
CREATE INDEX idx_payments_date     ON payments(payment_date DESC);
CREATE INDEX idx_messages_status   ON messages(status);
CREATE INDEX idx_admin_auth        ON admin_users(auth_user_id);
CREATE INDEX idx_activity_actor    ON activity_log(actor_type, actor_email);
CREATE INDEX idx_activity_created  ON activity_log(created_at DESC);

-- ══════════════════════════════════════════════════════════════
--  HELPER FUNCTIONS
-- ══════════════════════════════════════════════════════════════

-- Returns true if the currently authenticated user is a linked,
-- active admin. SECURITY DEFINER so it can read admin_users
-- without needing a separate RLS policy exposed to everyone
-- (avoids recursive-policy problems too).
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM admin_users au
    WHERE au.auth_user_id = auth.uid() AND au.active = true
  );
$$;

-- Called once, right after an admin signs in with Supabase Auth
-- (email + password). Links the auth account to the admin_users
-- row on first login (matched by email), refuses if the email
-- isn't a known/active admin, updates last_login, and writes an
-- 'admin_login' activity entry. This replaces the old hard-coded
-- ADMIN_EMAIL / ADMIN_PASS check that used to live in admin.html.
CREATE OR REPLACE FUNCTION admin_login_check()
RETURNS TABLE(ok BOOLEAN, admin_name TEXT, admin_role TEXT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_email TEXT := auth.jwt() ->> 'email';
  v_row   admin_users;
BEGIN
  IF auth.uid() IS NULL OR v_email IS NULL THEN
    RETURN QUERY SELECT false, NULL::TEXT, NULL::TEXT; RETURN;
  END IF;

  SELECT * INTO v_row FROM admin_users WHERE lower(email) = lower(v_email) AND active = true LIMIT 1;
  IF v_row.id IS NULL THEN
    RETURN QUERY SELECT false, NULL::TEXT, NULL::TEXT; RETURN;
  END IF;

  IF v_row.auth_user_id IS NULL THEN
    UPDATE admin_users SET auth_user_id = auth.uid(), last_login = now() WHERE id = v_row.id;
  ELSIF v_row.auth_user_id <> auth.uid() THEN
    -- email is registered to a different auth account — refuse
    RETURN QUERY SELECT false, NULL::TEXT, NULL::TEXT; RETURN;
  ELSE
    UPDATE admin_users SET last_login = now() WHERE id = v_row.id;
  END IF;

  INSERT INTO activity_log(actor_type, actor_email, action, details)
  VALUES ('admin', v_email, 'admin_login', NULL);

  RETURN QUERY SELECT true, v_row.name, v_row.role;
END;
$$;
GRANT EXECUTE ON FUNCTION admin_login_check() TO authenticated;

-- Lets any signed-in user (admin or client) log an activity event
-- about themselves — used by login.html / admin.html to record
-- 'login' and 'logout' (signup + email-verified are logged
-- automatically by the auth.users triggers below).
CREATE OR REPLACE FUNCTION log_activity(
  p_action      TEXT,
  p_details     TEXT DEFAULT NULL,
  p_entity_type TEXT DEFAULT NULL,
  p_entity_id   UUID DEFAULT NULL
) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_email TEXT := auth.jwt() ->> 'email';
  v_type  TEXT;
BEGIN
  IF auth.uid() IS NULL OR v_email IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  v_type := CASE WHEN is_admin() THEN 'admin' ELSE 'client' END;
  INSERT INTO activity_log (actor_type, actor_email, action, entity_type, entity_id, details)
  VALUES (v_type, v_email, p_action, p_entity_type, p_entity_id, p_details);
END;
$$;
GRANT EXECUTE ON FUNCTION log_activity(TEXT,TEXT,TEXT,UUID) TO authenticated;

-- Public loan-application submission. This is the ONLY way the
-- public website is allowed to write clients / loan_applications
-- rows (see RLS below) — it validates input, finds-or-creates the
-- client, creates the application, and logs it, all atomically and
-- without ever exposing the clients table to direct anon access.
CREATE OR REPLACE FUNCTION submit_loan_application(
  p_full_name          TEXT,
  p_email              TEXT,
  p_nif                TEXT,
  p_phone              TEXT,
  p_address             TEXT,
  p_date_of_birth       DATE,
  p_nationality         TEXT,
  p_residence_status    TEXT,
  p_id_document_type    TEXT,
  p_id_document_number  TEXT,
  p_monthly_income      NUMERIC,
  p_iban                TEXT,
  p_employment_status   TEXT,
  p_loan_type           TEXT,
  p_amount              NUMERIC,
  p_term_months         INTEGER,
  p_annual_rate         NUMERIC,
  p_loan_purpose        TEXT,
  p_existing_debts      NUMERIC
) RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_client_id UUID;
  v_app_no    TEXT;
  v_code      TEXT;
BEGIN
  IF p_full_name IS NULL OR length(trim(p_full_name)) < 2 THEN
    RAISE EXCEPTION 'Nome inválido';
  END IF;
  IF p_email IS NULL OR p_email !~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$' THEN
    RAISE EXCEPTION 'Email inválido';
  END IF;
  IF p_nif IS NULL OR p_nif !~ '^[0-9]{9}$' THEN
    RAISE EXCEPTION 'NIF inválido';
  END IF;
  IF p_loan_type NOT IN ('personal','mortgage','car','consolidation') THEN
    RAISE EXCEPTION 'Tipo de crédito inválido';
  END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Montante inválido';
  END IF;
  IF p_term_months IS NULL OR p_term_months <= 0 THEN
    RAISE EXCEPTION 'Prazo inválido';
  END IF;

  SELECT id INTO v_client_id FROM clients
  WHERE nif = p_nif OR email = p_email
  ORDER BY (nif = p_nif) DESC LIMIT 1;

  IF v_client_id IS NULL THEN
    v_code := 'C-' || to_char(now(),'YY') || lpad(nextval('client_code_seq')::text, 6, '0');
    INSERT INTO clients (
      client_code, full_name, email, nif, phone, address, date_of_birth,
      monthly_income, nationality, residence_status, id_document_type,
      id_document_number, iban, employment_status, status
    ) VALUES (
      v_code, p_full_name, p_email, p_nif, p_phone, p_address, p_date_of_birth,
      p_monthly_income, p_nationality, p_residence_status, p_id_document_type,
      p_id_document_number, p_iban, p_employment_status, 'active'
    ) RETURNING id INTO v_client_id;
  ELSE
    UPDATE clients SET
      full_name          = p_full_name,
      phone              = COALESCE(p_phone, phone),
      address            = COALESCE(p_address, address),
      date_of_birth      = COALESCE(p_date_of_birth, date_of_birth),
      monthly_income     = COALESCE(p_monthly_income, monthly_income),
      nationality        = COALESCE(p_nationality, nationality),
      residence_status   = COALESCE(p_residence_status, residence_status),
      id_document_type   = COALESCE(p_id_document_type, id_document_type),
      id_document_number = COALESCE(p_id_document_number, id_document_number),
      iban               = COALESCE(p_iban, iban),
      employment_status  = COALESCE(p_employment_status, employment_status)
    WHERE id = v_client_id;
  END IF;

  v_app_no := 'CR-' || to_char(now(),'YYYY') || '-' || lpad(nextval('application_no_seq')::text, 5, '0');

  INSERT INTO loan_applications (
    application_no, client_id, loan_type, amount, term_months, annual_rate,
    loan_purpose, existing_debts, source, status
  ) VALUES (
    v_app_no, v_client_id, p_loan_type, p_amount, p_term_months, p_annual_rate,
    p_loan_purpose, COALESCE(p_existing_debts, 0), 'website', 'pending'
  );

  INSERT INTO activity_log (actor_type, actor_email, action, entity_type, details)
  VALUES ('system', p_email, 'application_submitted', 'application', v_app_no);

  RETURN v_app_no;
END;
$$;
GRANT EXECUTE ON FUNCTION submit_loan_application(
  TEXT,TEXT,TEXT,TEXT,TEXT,DATE,TEXT,TEXT,TEXT,TEXT,NUMERIC,TEXT,TEXT,TEXT,NUMERIC,INTEGER,NUMERIC,TEXT,NUMERIC
) TO anon, authenticated;

-- Lets an admin add a client manually from the admin panel (the
-- "Novo Cliente" modal) with the same server-generated client_code
-- scheme used by submit_loan_application, instead of the panel
-- inserting rows directly (which used to silently do nothing).
CREATE OR REPLACE FUNCTION admin_create_client(
  p_full_name      TEXT,
  p_email          TEXT,
  p_nif            TEXT,
  p_phone          TEXT,
  p_address        TEXT,
  p_date_of_birth  DATE,
  p_monthly_income NUMERIC
) RETURNS UUID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_client_id UUID;
  v_code      TEXT;
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Apenas administradores podem criar clientes manualmente';
  END IF;
  IF p_full_name IS NULL OR length(trim(p_full_name)) < 2 THEN RAISE EXCEPTION 'Nome inválido'; END IF;
  IF p_email IS NULL OR p_email !~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$' THEN RAISE EXCEPTION 'Email inválido'; END IF;
  IF p_nif IS NULL OR p_nif !~ '^[0-9]{9}$' THEN RAISE EXCEPTION 'NIF inválido'; END IF;

  v_code := 'C-' || to_char(now(),'YY') || lpad(nextval('client_code_seq')::text, 6, '0');
  INSERT INTO clients (client_code, full_name, email, nif, phone, address, date_of_birth, monthly_income, status)
  VALUES (v_code, p_full_name, p_email, p_nif, p_phone, p_address, p_date_of_birth, p_monthly_income, 'active')
  RETURNING id INTO v_client_id;

  INSERT INTO activity_log (actor_type, actor_email, action, entity_type, entity_id, details)
  VALUES ('admin', auth.jwt() ->> 'email', 'created_client', 'client', v_client_id, p_full_name);

  RETURN v_client_id;
END;
$$;
GRANT EXECUTE ON FUNCTION admin_create_client(TEXT,TEXT,TEXT,TEXT,TEXT,DATE,NUMERIC) TO authenticated;

-- Auto-log account creation the moment Supabase Auth creates the
-- user (fires before the person ever calls the app again), and
-- auto-log the moment their email gets confirmed.
CREATE OR REPLACE FUNCTION handle_new_auth_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO activity_log (actor_type, actor_email, action, details)
  VALUES ('client', NEW.email, 'signup', 'Conta criada');
  RETURN NEW;
END;
$$;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_auth_user();

CREATE OR REPLACE FUNCTION handle_auth_user_verified()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF OLD.email_confirmed_at IS NULL AND NEW.email_confirmed_at IS NOT NULL THEN
    INSERT INTO activity_log (actor_type, actor_email, action, details)
    VALUES ('client', NEW.email, 'email_verified', 'Email confirmado');
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER on_auth_user_verified
  AFTER UPDATE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_auth_user_verified();

-- ══════════════════════════════════════════════════════════════
--  ROW LEVEL SECURITY
-- ══════════════════════════════════════════════════════════════
ALTER TABLE clients               ENABLE ROW LEVEL SECURITY;
ALTER TABLE loan_applications     ENABLE ROW LEVEL SECURITY;
ALTER TABLE loans                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments              ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages              ENABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users           ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings       ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_log          ENABLE ROW LEVEL SECURITY;

-- clients — no direct public INSERT anymore (goes through
-- submit_loan_application). A signed-in client can see / update
-- their own record (matched by auth_user_id, or by email on their
-- very first login before the link is made); an admin can see/edit
-- everyone.
CREATE POLICY "clients_select" ON clients FOR SELECT
  USING (is_admin() OR auth.uid() = auth_user_id OR email = (auth.jwt() ->> 'email'));
CREATE POLICY "clients_update" ON clients FOR UPDATE
  USING (is_admin() OR auth.uid() = auth_user_id OR (auth_user_id IS NULL AND email = (auth.jwt() ->> 'email')))
  WITH CHECK (is_admin() OR auth.uid() = auth_user_id);
CREATE POLICY "clients_insert_admin" ON clients FOR INSERT
  WITH CHECK (is_admin());

-- loan_applications — same idea: public submission via RPC only;
-- the owning client can read their own applications; only admins
-- can change status.
CREATE POLICY "apps_select" ON loan_applications FOR SELECT
  USING (
    is_admin() OR EXISTS (
      SELECT 1 FROM clients c WHERE c.id = loan_applications.client_id
        AND (c.auth_user_id = auth.uid() OR c.email = (auth.jwt() ->> 'email'))
    )
  );
CREATE POLICY "apps_update_admin" ON loan_applications FOR UPDATE USING (is_admin());
CREATE POLICY "apps_insert_admin" ON loan_applications FOR INSERT WITH CHECK (is_admin());

-- loans — owning client can view; only admin can write.
CREATE POLICY "loans_select" ON loans FOR SELECT
  USING (
    is_admin() OR EXISTS (
      SELECT 1 FROM clients c WHERE c.id = loans.client_id
        AND (c.auth_user_id = auth.uid() OR c.email = (auth.jwt() ->> 'email'))
    )
  );
CREATE POLICY "loans_insert_admin" ON loans FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "loans_update_admin" ON loans FOR UPDATE USING (is_admin());

-- payments — owning client can view; only admin can write.
CREATE POLICY "payments_select" ON payments FOR SELECT
  USING (
    is_admin() OR EXISTS (
      SELECT 1 FROM clients c WHERE c.id = payments.client_id
        AND (c.auth_user_id = auth.uid() OR c.email = (auth.jwt() ->> 'email'))
    )
  );
CREATE POLICY "payments_insert_admin" ON payments FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "payments_update_admin" ON payments FOR UPDATE USING (is_admin());

-- messages — anyone can send a contact message; only admin reads/replies.
CREATE POLICY "messages_insert" ON messages FOR INSERT WITH CHECK (true);
CREATE POLICY "messages_select_admin" ON messages FOR SELECT USING (is_admin());
CREATE POLICY "messages_update_admin" ON messages FOR UPDATE USING (is_admin());

-- newsletter — anyone can subscribe; only admin manages the list.
CREATE POLICY "newsletter_insert" ON newsletter_subscribers FOR INSERT WITH CHECK (true);
CREATE POLICY "newsletter_select_admin" ON newsletter_subscribers FOR SELECT USING (is_admin());
CREATE POLICY "newsletter_update_admin" ON newsletter_subscribers FOR UPDATE USING (is_admin());
CREATE POLICY "newsletter_delete_admin" ON newsletter_subscribers FOR DELETE USING (is_admin());

-- admin_users — admins only (bootstrap/self-link happens through
-- admin_login_check(), which runs as SECURITY DEFINER and so does
-- not need a table policy to work).
CREATE POLICY "admin_select" ON admin_users FOR SELECT USING (is_admin());
CREATE POLICY "admin_insert" ON admin_users FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "admin_update" ON admin_users FOR UPDATE USING (is_admin());

-- system_settings — publicly readable (rates/limits are shown on
-- the public site), only admins can change them.
CREATE POLICY "settings_select" ON system_settings FOR SELECT USING (true);
CREATE POLICY "settings_update_admin" ON system_settings FOR UPDATE USING (is_admin());

-- activity_log — admins can read everything (that's the point of
-- the activity feed). Rows are written by SECURITY DEFINER
-- functions/triggers (bypassing RLS) or directly by an
-- authenticated admin performing an action in the panel.
CREATE POLICY "activity_select_admin" ON activity_log FOR SELECT USING (is_admin());
CREATE POLICY "activity_insert_admin" ON activity_log FOR INSERT WITH CHECK (is_admin());

-- ══════════════════════════════════════════════════════════════
--  VIEWS
-- ══════════════════════════════════════════════════════════════
CREATE OR REPLACE VIEW vw_dashboard_summary AS
SELECT
  (SELECT COUNT(*) FROM clients WHERE status = 'active')                                   AS active_clients,
  (SELECT COUNT(*) FROM loan_applications WHERE status = 'pending')                        AS pending_applications,
  (SELECT COUNT(*) FROM loan_applications WHERE status = 'review')                         AS review_applications,
  (SELECT COUNT(*) FROM loans WHERE status = 'active')                                     AS active_loans,
  (SELECT COUNT(*) FROM loans WHERE status = 'defaulted')                                  AS defaulted_loans,
  (SELECT COALESCE(SUM(principal),0) FROM loans WHERE status='active')                     AS total_portfolio,
  (SELECT COALESCE(SUM(amount),0) FROM payments WHERE status='paid'
     AND DATE_TRUNC('month',payment_date)=DATE_TRUNC('month',CURRENT_DATE))                AS received_this_month,
  (SELECT COUNT(*) FROM messages WHERE status='unread')                                    AS unread_messages,
  (SELECT COUNT(*) FROM newsletter_subscribers WHERE subscribed=true)                      AS newsletter_count,
  (SELECT COUNT(*) FROM activity_log WHERE actor_type='client' AND action='signup'
     AND created_at >= CURRENT_DATE)                                                       AS signups_today;

CREATE OR REPLACE VIEW vw_applications_full AS
SELECT
  la.id, la.application_no, la.loan_type, la.amount, la.term_months,
  ROUND(la.annual_rate*100,4) AS tan_percent,
  la.status, la.notes, la.loan_purpose, la.existing_debts, la.source,
  la.created_at, la.reviewed_at, la.reviewed_by,
  c.id AS client_id, c.full_name AS client_name, c.email AS client_email,
  c.nif AS client_nif, c.phone AS client_phone,
  c.monthly_income, c.nationality, c.residence_status,
  c.id_document_type, c.id_document_number, c.iban,
  c.employment_status, c.date_of_birth, c.address, c.kyc_verified
FROM loan_applications la
JOIN clients c ON la.client_id = c.id
ORDER BY la.created_at DESC;

CREATE OR REPLACE VIEW vw_payments_full AS
SELECT
  p.id, p.payment_ref, p.amount, p.payment_method,
  p.payment_date, p.status, p.notes, p.created_at,
  l.contract_no, l.loan_type,
  c.full_name AS client_name, c.email AS client_email, c.phone AS client_phone
FROM payments p
JOIN loans   l ON p.loan_id=l.id
JOIN clients c ON p.client_id=c.id
ORDER BY p.payment_date DESC, p.created_at DESC;

CREATE OR REPLACE VIEW vw_clients_overview AS
SELECT
  c.id, c.client_code, c.full_name, c.email, c.nif, c.phone,
  c.status, c.kyc_verified, c.employment_status, c.monthly_income, c.created_at,
  COUNT(DISTINCT la.id)                                            AS total_applications,
  COUNT(DISTINCT l.id) FILTER (WHERE l.status='active')           AS active_loans,
  COALESCE(SUM(l.principal) FILTER (WHERE l.status='active'),0)   AS total_borrowed
FROM clients c
LEFT JOIN loan_applications la ON la.client_id=c.id
LEFT JOIN loans l ON l.client_id=c.id
GROUP BY c.id ORDER BY c.created_at DESC;

-- Unified feed used by Admin → Atividade: admin actions AND
-- client account activity (signup / email verified / login / logout).
CREATE OR REPLACE VIEW vw_activity_feed AS
SELECT id, actor_type, actor_email, action, entity_type, entity_id, details, created_at
FROM activity_log
ORDER BY created_at DESC;

-- ══════════════════════════════════════════════════════════════
--  DEFAULT DATA
-- ══════════════════════════════════════════════════════════════
-- ⚠️ This only creates the admin_users ROW — it does not create a
-- Supabase Auth login. After running this script, go to
-- Authentication → Users → Add user in the Supabase dashboard and
-- create a user with this same email (and a strong password you
-- choose). The very first time that account signs in through
-- pages/admin.html, admin_login_check() links the two together
-- automatically. See INSTRUCTIONS.md for the full walkthrough.
INSERT INTO admin_users (email, name, role) VALUES
  ('admin@creditxa.pt','Administrador Principal','super_admin')
ON CONFLICT (email) DO NOTHING;

INSERT INTO system_settings (key,value,description) VALUES
  ('tan_min_personal','7.99',   'TAN mínima — Pessoal (%)'),
  ('tan_max_personal','14.99',  'TAN máxima — Pessoal (%)'),
  ('tan_min_mortgage','3.09',   'TAN mínima — Habitação (%)'),
  ('tan_max_mortgage','5.00',   'TAN máxima — Habitação (%)'),
  ('tan_min_car',     '5.99',   'TAN mínima — Automóvel (%)'),
  ('tan_max_car',     '9.99',   'TAN máxima — Automóvel (%)'),
  ('tan_min_consol',  '6.49',   'TAN mínima — Consolidação (%)'),
  ('max_loan_personal','75000', 'Montante máximo — Pessoal (€)'),
  ('max_loan_mortgage','500000','Montante máximo — Habitação (€)'),
  ('max_loan_car',    '80000',  'Montante máximo — Automóvel (€)'),
  ('max_loan_consol', '150000', 'Montante máximo — Consolidação (€)'),
  ('max_term_personal','84',    'Prazo máximo — Pessoal (meses)'),
  ('max_term_mortgage','360',   'Prazo máximo — Habitação (meses)'),
  ('max_term_car',    '84',     'Prazo máximo — Automóvel (meses)'),
  ('max_dsr',         '35',     'Taxa de esforço máxima (%)'),
  ('notify_new_apps', 'true',   'Notificar admin — novos pedidos'),
  ('notify_overdue',  'true',   'Notificar admin — pagamentos em atraso'),
  ('session_timeout', '30',     'Timeout sessão admin (minutos)')
ON CONFLICT (key) DO NOTHING;
-- ================================================================
